[components]

is_zombie = { type = "Empty", attributes = ["Networked", "Debuggable"] }

zombie_step_frame_count = { type = "U32", attributes = [
    "Networked",
    "Debuggable",
] }

zombie_hit_reaction_count = { type = "I32", attributes = [
    "Networked",
    "Debuggable",
] }

zombie_health = { type = "I32", attributes = ["Networked", "Debuggable"] }

zombie_model_ref = { type = "EntityId", attributes = [
    "Networked",
    "Debuggable",
] }

[messages.hit_zombie.fields]
id = { type = "EntityId" }
